### ISSUE TITLE
Scrolling contents

### ISSUE THREAD

**Issue by orhun** [joshka/tui-popup#16]
Is there a way to scroll the lines inside the popup?

Any ideas?

**Comment by joshka** [comment]
No not right now. I'm not sure whether it's a good idea to add complexity as this is a really simple widget right now.
But I can see how this would make it easy to show help text or longer messages. Feel free to spec it out / implement.
One problem I'd foresee is there might end up being a lot of overlap with the `Paragraph` widget.

**Comment by orhun** [comment]
I have a hacky solution for this now, and you might be right about overlapping the functionality with the `Paragraph` widget. 

I might come back to this later in the future. I'd say let's keep this open in case someone else hits the same issue.

**Comment by joshka** [comment]
A slightly less hacky solution to this is to make the body of the popup support rendering any widget instead of just Text.
It's possible to do this, but currently the popup supports autosizing based on the contents, so to continue to support that it would be necessary to make a sized widget trait and implement that for Text / etc.
